### ISSUE TITLE
Pouvoir lier plusieurs jeux de données entre eux

### ISSUE THREAD

**Issue by cquest** [etalab/etalab-support#15]
Un producteur devrait pouvoir lier plusieurs jeux de données entre eux pour faire ce que j'ai fait manuellement sur les différents contours géographiques d'OSM:

Exemple: https://www.data.gouv.fr/fr/dataset/contours-des-regions-francaises-sur-openstreetmap

**Comment by noirbizarre** [comment]
This issue was moved to etalab/data.gouv.fr#16
