### ISSUE TITLE
Pouvoir lier une réutilisation à plusieurs jeux de données

### ISSUE THREAD

**Issue by cquest** [etalab/etalab-support#16]
Lorsqu'une réutilisation se base sur plusieurs jeux de données, il serait utile de pouvoir l'indiquer directement.

Ceci permettrait aussi d'avoir une vue des croisements de données réalisés et d'afiner la notation (les jeux de données que l'on croise sont un bon indice de qualité et d'utilité).

**Comment by noirbizarre** [comment]
This issue was moved to etalab/data.gouv.fr#8
