### ISSUE TITLE
Supprimer son profil sur data.gouv.fr

### ISSUE THREAD

**Issue by ColinMaudry** [etalab/etalab-support#19]
Hello,

Aujourd'hui je me suis créé un profil sur data.gouv.fr alors que je m'en étais créé un il y a bien longtemps.

A cette occasion je le suis rendu compte qu'li n'y avait pas d'options pour supprimer son compte. Ou ai-je mal cherché ?

**Comment by noirbizarre** [comment]
This issue was moved to etalab/data.gouv.fr#15
