### ISSUE TITLE
contacter une organisation

### ISSUE THREAD

**Issue by Cyrille37** [etalab/etalab-support#21]
Bonjour,
Ça serait de pouvoir laisser un message aux organisations inscrites sur data.gouv.fr.
Par exemple j'aimerais demander à l'organisation [Pôle Emploi](https://www.data.gouv.fr/fr/organizations/pole-emploi/) l'annuaire des agences Pôle Emploi.
Ou alors activer les discussions comme pour les jeux de données ?
Merci.

**Comment by noirbizarre** [comment]
This issue was moved to etalab/data.gouv.fr#7
