### ISSUE TITLE
problème avec blason

### ISSUE THREAD

**Issue by Cyrille37** [etalab/etalab-support#22]
Bonjour,
pour la commune [37158 Montreuil-en-Touraine](https://www.data.gouv.fr/fr/town/37158/) le blason n'apparait pas alors qu'il est bien sur [wikipedia](https://fr.wikipedia.org/wiki/Montreuil-en-Touraine).
La seule différence que je vois avec les autres blasons qui fonctionnent sur data.gouv.fr est qu'il est sous licence CC0 ...
Cheers.

**Comment by noirbizarre** [comment]
This issue was moved to etalab/data.gouv.fr#4
