### ISSUE TITLE
Pouvoir télécharger tous les fichiers d'une page d'un coup

### ISSUE THREAD

**Issue by letailli** [etalab/etalab-support#4]
Pour des pages avec de nombreux fichiers. Exemple :
http://www.etalab2.fr/fr/dataset/effectifs-d-etudiants-inscrits-dans-les-etablissements-et-les-formations-de-l-enseignement-superieur

**Comment by noirbizarre** [comment]
This issue was moved to etalab/data.gouv.fr#13
