### ISSUE TITLE
Ajout de ressource sur un jeu de donnée que l'on n'a pas créé

### ISSUE THREAD

**Issue by cquest** [etalab/etalab-support#6]
Sur https://www.data.gouv.fr/fr/dataset/videosurveillance-en-france qui n'avait aucune ressource (peut être une piste) j'ai ajouté une ressource dans la partie contribution de la communauté (en bas) et elle s'est retrouvée dans les ressources du jeu de donnée.
De plus, j'ai maintenant l'accès à l'édition du jeu de données... problème de gestion des droits ?

**Comment by noirbizarre** [comment]
This issue was moved to etalab/data.gouv.fr#12
