### ISSUE TITLE
Internal server error sur ajout d'une réutilisation

### ISSUE THREAD

**Issue by cquest** [etalab/etalab-support#7]
En ajoutant une réutilisation sur https://www.data.gouv.fr/fr/dataset/decoupage-administratif-communal-francais-issu-d-openstreetmap
 j'aboutit sur https://www.data.gouv.fr/fr/dataset/decoupage-administratif-communal-francais-issu-d-openstreetmap/related/new avec une Internal Server Error (et un message en anglais invitant à contacter  webmaster+www@data.gouv.fr )

20-12-2013 16h: ça semble ok maintenant, vous pouvez fermer !

**Comment by noirbizarre** [comment]
This issue was moved to etalab/data.gouv.fr#10
